---
title: Workshops
css: cscar.css
---

CSCAR does a lot of [workshops](http://cscar.research.umich.edu/events/category/workshops/). Like, *really* a lot. This is where you can find web pages/sites of CSCAR members that specifically house materials for workshops, like slides, code etc.  Listed are the primary programming languages covered.


[Alex Cao](https://github.com/caocscar) Python

[Michael Clark](https://m-clark.github.io/workshops/) R, Stan

[Josh Errickson](https://github.com/josherrickson) R, Stata

[James Henderson](https://github.com/jbhender/Workshops) R, C++

[Andrew Hlynka](https://www.fromdustscratch.com/) C#, Unity3d

[Marcio Mourao](https://marcio-mourao.github.io/) Python, Matlab

[Kerby Shedden](https://kshedden.github.io/) Python, Go

[Gregory Teichert](https://github.com/greght) Python, C++


## Data Science Skills Series

We conduct the *Data Science Skills Series*, which are typically two-hour free workshops on any number of topics. Here are some of the topics that have been covered or soon will be.

### R

Data Processing and Visualization, Engaging the Web, Generalized Additive Models, tidyverse, Bayesian modeling with R & Stan, Getting more from RStudio, Parallel Computing, Dimension Reduction techniques, Intro to Rcpp, Developing R packages


### Python

Data Processing and Visualization, Unsupervised Learning,  Supervised Learning, Regular Expressions, Engaging the Web, Mixed Models, GEE, Multiple imputation and missing data methods, Mediation analysis, GeoPandas, Network Analysis, Numpy


### Matlab

Introduction to Matlab, Intermediate Matlab

### Other

GIS and spatial analysis, Introduction to GO, Intermediate GO. Note that ARC-TS (the high performance computing group) provides workshops specific to working with their environment (e.g. cluster computing).



## Traditional Workshops

In the past CSCAR gave paid for workshops that were longer lasting, often taking place over multiple full or half days, and are definitely hands on.  The following is a list of topics covered.  It is possible to schedule one of these for your specific research group.


Introduction to Statistical Analysis in R

Several introductions to statistical packages: SAS, SPSS, Stata

Mixed Models in SPSS

Mixed Models in R

Introduction to survey design

Structural Equation Modeling (3 part series including graphical modeling, latent variables, and SEM)
